# Configuration the address on which the server listens
net.host = "0.0.0.0"
net.port = 6379
net.min_backoff_ms = 125
net.max_backoff_ms = 64000
net.max_connections = 1024

# Bitcask directory path
storage.path = "db"
# Bitcask number of concurrent readers
storage.concurrency = 8
# Bitcask readers cache size used by the writer and each of the readers
storage.readers_cache_size = 256
# Bitcask maximum allowed file size
storage.max_file_size = 2000000000

# Bitcask disk sync strategy (choose one)
################################
# disk sync is handled by the OS
################################
storage.sync = "none"
##########################################
# always force a sync after write
##########################################
#storage.sync = "always"
###########################################################################
# specify the interval in milliseconds in which sync is periodically called
###########################################################################
#storage.sync.interval_ms = 500

# Bitcask merge policy (choose one)
########################################
# always merge data files when triggered
########################################
storage.merge.policy = "always"
########################
# never merge data files
########################
#storage.merge.policy = "never"
###########################################################################
# only merge data files when triggered within the specifed time window
# this example configure merge to happen within 00:00:00 AM and 07:59:59 AM
###########################################################################
#storage.merge.policy.window.start = 0
#storage.merge.policy.window.end = 7

# Interval in which merge conditions are checked
storage.merge.check_interval_ms = 180000
# Jitter add/subtract a random fraction of the interval from itself
# so merges happen at irregular time intervals
storage.merge.check_jitter = 0.3

# The minimum fragmentation (fraction of dead keys to total keys) of a file
# that triggers a merge
storage.merge.triggers.fragmentation = 0.6
# The minimum number of dead bytes in a file that triggers a merge
storage.merge.triggers.dead_bytes = 512000000

# The minimum fragmentation (fraction of dead keys to total keys) of a file
# that causes it to be merged
storage.merge.thresholds.fragmentation = 0.4
# The minimum number of dead bytes in a file that causes it to be merged
storage.merge.thresholds.dead_bytes = 128000000
# The minimum size of a file that causes it to be excluded from a merge
storage.merge.thresholds.small_file = 10000000
